version: "3.9"
services:
  app:
    build: .
    image: das:${DAS_TAG:-latest}
    environment:
      - DAS_MONGODB_HOSTNAME=${DAS_MONGODB_HOSTNAME:-mongo}
      - DAS_MONGODB_PORT=${DAS_MONGODB_PORT:-27017}
      - DAS_COUCHBASE_HOSTNAME=${DAS_COUCHBASE_HOSTNAME:-couchbase}
      - DAS_DATABASE_USERNAME=${DAS_DATABASE_USERNAME:-dbadmin}
      - DAS_DATABASE_PASSWORD=${DAS_DATABASE_PASSWORD:-dassecret}
      - PYTHONPATH=/app
      - TZ=${TZ}
    tty: true
    volumes:
      - ./das:/app/das
      - ./tests:/app/tests
      - ./data:/app/data
      - /tmp:/tmp
      - /mnt:/mnt
      - /media:/media
    links:
      - mongo
      - couchbase

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DAS_DATABASE_USERNAME:-dbadmin}
      - MONGO_INITDB_ROOT_PASSWORD=${DAS_DATABASE_PASSWORD:-dassecret}
      - TZ=${TZ}
    ports:
      - ${DAS_MONGODB_PORT:-27017}:${DAS_MONGODB_PORT:-27017}
    volumes:
      - mongodbdata:/data/db
      - /tmp:/tmp
      - /mnt:/mnt
    command: mongod --port ${DAS_MONGODB_PORT:-27017}

  couchbase:
    image: couchbase
    build:
        context: .
        dockerfile: Dockerfile.couchbase
    environment:
      - DAS_DATABASE_USERNAME=${DAS_DATABASE_USERNAME:-dbadmin}
      - DAS_DATABASE_PASSWORD=${DAS_DATABASE_PASSWORD:-dassecret}
      - DAS_COUCHBASE_BUCKET_RAMSIZE=${DAS_COUCHBASE_BUCKET_RAMSIZE:-8192}
      - COUCHBASE_SETUP_DIR=/opt/couchbase_setup
      - TZ=${TZ}
    ports:
      - "8091-8095:8091-8095"
      - "11210:11210"
    expose:
      - "8091"
      - "8094"
    volumes:
      - /tmp:/tmp
      - /mnt:/mnt
      - couchbasedata:/opt/couchbase/var
      - couchbasesetup:/opt/couchbase_setup

volumes:
  mongodbdata: { }
  couchbasedata: { }
  couchbasesetup: { }
