version: "3.9"
services:
  app:
    build: .
    image: das:${DAS_TAG:-latest}
    environment:
      - DAS_MONGODB_HOSTNAME=${DAS_MONGODB_HOSTNAME:-mongo}
      - DAS_MONGODB_PORT=${DAS_MONGODB_PORT:-27017}
      - DAS_COUCHBASE_HOSTNAME=${DAS_COUCHBASE_HOSTNAME:-couchbase}
      - DAS_REDIS_HOSTNAME=${DAS_REDIS_HOSTNAME:-redis}
      - DAS_REDIS_PORT=${DAS_REDIS_PORT:-6379}
      - DAS_DATABASE_USERNAME=${DAS_DATABASE_USERNAME:-dbadmin}
      - DAS_DATABASE_PASSWORD=${DAS_DATABASE_PASSWORD:-dassecret}
      - PYTHONPATH=/app
      - TZ=${TZ}
    tty: true
    network_mode: "host"
    volumes:
      - ./das:/app/das
      - ./tests:/app/tests
      - ./data:/app/data
      - ./notebooks:/app/notebooks
      - /tmp:/tmp
      - /mnt:/mnt
      - /media:/media

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DAS_DATABASE_USERNAME:-dbadmin}
      - MONGO_INITDB_ROOT_PASSWORD=${DAS_DATABASE_PASSWORD:-dassecret}
      - TZ=${TZ}
    network_mode: "host"
    volumes:
      - mongodbdata:/data/db
      - /tmp:/tmp
      - /mnt:/mnt
    command: mongod --port ${DAS_MONGODB_PORT:-27017}

  redis:
    image: redis/redis-stack
    environment:
      - DAS_REDIS_HOSTNAME=${DAS_REDIS_HOSTNAME:-redis}
      - DAS_REDIS_PORT=${DAS_REDIS_PORT:-6379}
      - TZ=${TZ}
    network_mode: "host"
    volumes:
      - /tmp:/tmp
      - /mnt:/mnt

volumes:
  mongodbdata: { }
  couchbasedata: { }
  couchbasesetup: { }
